import 'dart:ui' show Rect;

import 'package:flutter_test/flutter_test.dart';
import 'package:fplayer/src/storyboard/storyboard_vtt.dart';

void main() {
  group('parseStoryboardVtt', () {
    test('parses sprite cues with #xywh regions', () {
      const vtt = '''
WEBVTT

00:00:00.000 --> 00:00:05.000
sheet-0.jpg#xywh=0,0,160,90

00:00:05.000 --> 00:00:10.000
sheet-0.jpg#xywh=160,0,160,90
''';

      final storyboard = parseStoryboardVtt(vtt);

      expect(storyboard.length, 2);
      expect(storyboard.frames.first.start, Duration.zero);
      expect(storyboard.frames.first.end, const Duration(seconds: 5));
      expect(storyboard.frames.first.url, 'sheet-0.jpg');
      expect(storyboard.frames.first.region, const Rect.fromLTWH(0, 0, 160, 90));
      expect(storyboard.frames.last.region, const Rect.fromLTWH(160, 0, 160, 90));
    });

    test('accepts the pixel: prefix on the media fragment', () {
      const vtt = '''
WEBVTT

00:00:00.000 --> 00:00:05.000
sheet.jpg#xywh=pixel:10,20,160,90
''';

      expect(
        parseStoryboardVtt(vtt).frames.single.region,
        const Rect.fromLTWH(10, 20, 160, 90),
      );
    });

    test('falls back to the whole image for percent: regions', () {
      const vtt = '''
WEBVTT

00:00:00.000 --> 00:00:05.000
sheet.jpg#xywh=percent:0,0,25,25
''';

      final frame = parseStoryboardVtt(vtt).frames.single;
      expect(frame.url, 'sheet.jpg');
      expect(frame.region, isNull);
    });

    test('supports one file per thumbnail', () {
      const vtt = '''
WEBVTT

00:00:00.000 --> 00:00:05.000
thumbs/0001.jpg

00:00:05.000 --> 00:00:10.000
thumbs/0002.jpg
''';

      final storyboard = parseStoryboardVtt(vtt);
      expect(storyboard.length, 2);
      expect(storyboard.frames.every((f) => f.region == null), isTrue);
      expect(storyboard.frames.last.url, 'thumbs/0002.jpg');
    });

    test('resolves relative urls against the index location', () {
      const vtt = '''
WEBVTT

00:00:00.000 --> 00:00:05.000
sheet-0.jpg#xywh=0,0,160,90

00:00:05.000 --> 00:00:10.000
../shared/sheet-1.jpg#xywh=0,0,160,90

00:00:10.000 --> 00:00:15.000
https://other.example.com/absolute.jpg#xywh=0,0,160,90
''';

      final storyboard = parseStoryboardVtt(
        vtt,
        baseUri: Uri.parse('https://cdn.example.com/media/ep1/storyboard.vtt'),
      );

      expect(
        storyboard.frames[0].url,
        'https://cdn.example.com/media/ep1/sheet-0.jpg',
      );
      expect(
        storyboard.frames[1].url,
        'https://cdn.example.com/media/shared/sheet-1.jpg',
      );
      expect(
        storyboard.frames[2].url,
        'https://other.example.com/absolute.jpg',
      );
    });

    test('strips a UTF-8 BOM and handles CRLF line endings', () {
      const vtt = '﻿WEBVTT\r\n'
          '\r\n'
          '00:00:00.000 --> 00:00:05.000\r\n'
          'sheet.jpg#xywh=0,0,160,90\r\n';

      final storyboard = parseStoryboardVtt(vtt);
      expect(storyboard.length, 1);
      expect(storyboard.frames.single.url, 'sheet.jpg');
      expect(storyboard.frames.single.region, const Rect.fromLTWH(0, 0, 160, 90));
    });

    test('handles lone CR line endings', () {
      const vtt = 'WEBVTT\r\r00:00:00.000 --> 00:00:05.000\rsheet.jpg\r';

      expect(parseStoryboardVtt(vtt).length, 1);
    });

    test('skips the header metadata block', () {
      const vtt = '''
WEBVTT - Storyboard for episode 1
Kind: metadata
Language: en

00:00:00.000 --> 00:00:05.000
sheet.jpg
''';

      final storyboard = parseStoryboardVtt(vtt);
      expect(storyboard.length, 1);
      expect(storyboard.frames.single.url, 'sheet.jpg');
    });

    test('skips NOTE, STYLE and REGION blocks', () {
      const vtt = '''
WEBVTT

NOTE
Generated by some packager.

NOTE this one is inline

STYLE
::cue { color: white }

REGION
id:thumbs

00:00:00.000 --> 00:00:05.000
sheet.jpg
''';

      final storyboard = parseStoryboardVtt(vtt);
      expect(storyboard.length, 1);
      expect(storyboard.frames.single.url, 'sheet.jpg');
    });

    test('ignores cue identifiers', () {
      const vtt = '''
WEBVTT

1
00:00:00.000 --> 00:00:05.000
sheet.jpg#xywh=0,0,160,90

thumb-two
00:00:05.000 --> 00:00:10.000
sheet.jpg#xywh=160,0,160,90
''';

      final storyboard = parseStoryboardVtt(vtt);
      expect(storyboard.length, 2);
      expect(storyboard.frames.last.region, const Rect.fromLTWH(160, 0, 160, 90));
    });

    test('accepts timestamps with and without an hours component', () {
      const vtt = '''
WEBVTT

00:00.000 --> 00:05.000
a.jpg

01:02:03.400 --> 01:02:08.000
b.jpg
''';

      final storyboard = parseStoryboardVtt(vtt);
      expect(storyboard.frames.first.start, Duration.zero);
      expect(storyboard.frames.first.end, const Duration(seconds: 5));
      expect(
        storyboard.frames.last.start,
        const Duration(hours: 1, minutes: 2, seconds: 3, milliseconds: 400),
      );
    });

    test('accepts a comma as the decimal separator', () {
      const vtt = '''
WEBVTT

00:00:00,000 --> 00:00:05,500
sheet.jpg
''';

      expect(
        parseStoryboardVtt(vtt).frames.single.end,
        const Duration(seconds: 5, milliseconds: 500),
      );
    });

    test('ignores cue settings after the end timestamp', () {
      const vtt = '''
WEBVTT

00:00:00.000 --> 00:00:05.000 align:start line:90%
sheet.jpg
''';

      final frame = parseStoryboardVtt(vtt).frames.single;
      expect(frame.end, const Duration(seconds: 5));
      expect(frame.url, 'sheet.jpg');
    });

    test('skips malformed blocks without losing the rest of the file', () {
      const vtt = '''
WEBVTT

00:00:00.000 --> 00:00:05.000
good-1.jpg

not a timing line at all
neither is this

00:00:05.000 --> banana
broken-timing.jpg

00:00:15.000 --> 00:00:10.000
reversed.jpg

00:00:20.000 --> 00:00:25.000

00:00:10.000 --> 00:00:15.000
good-2.jpg
''';

      final storyboard = parseStoryboardVtt(vtt);
      expect(storyboard.frames.map((f) => f.url), ['good-1.jpg', 'good-2.jpg']);
    });

    test('keeps unrecognised fragments on the url', () {
      const vtt = '''
WEBVTT

00:00:00.000 --> 00:00:05.000
sheet.jpg#t=1,2
''';

      expect(parseStoryboardVtt(vtt).frames.single.url, 'sheet.jpg#t=1,2');
    });

    test('rejects regions with a non-positive size', () {
      const vtt = '''
WEBVTT

00:00:00.000 --> 00:00:05.000
sheet.jpg#xywh=0,0,0,90
''';

      final frame = parseStoryboardVtt(vtt).frames.single;
      expect(frame.url, 'sheet.jpg');
      expect(frame.region, isNull);
    });

    test('parses a file with no WEBVTT header', () {
      const vtt = '''
00:00:00.000 --> 00:00:05.000
sheet.jpg
''';

      expect(parseStoryboardVtt(vtt).length, 1);
    });

    test('returns an empty storyboard for junk input', () {
      expect(parseStoryboardVtt('').isEmpty, isTrue);
      expect(parseStoryboardVtt('not a vtt file at all').isEmpty, isTrue);
    });

    test('tolerates extra blank lines between cues', () {
      const vtt = '''
WEBVTT



00:00:00.000 --> 00:00:05.000
a.jpg



00:00:05.000 --> 00:00:10.000
b.jpg
''';

      expect(parseStoryboardVtt(vtt).length, 2);
    });

    test('sorts frames by start position', () {
      const vtt = '''
WEBVTT

00:00:10.000 --> 00:00:15.000
c.jpg

00:00:00.000 --> 00:00:05.000
a.jpg

00:00:05.000 --> 00:00:10.000
b.jpg
''';

      expect(
        parseStoryboardVtt(vtt).frames.map((f) => f.url),
        ['a.jpg', 'b.jpg', 'c.jpg'],
      );
    });
  });
}
