import 'dart:ui' show Rect;

import 'storyboard.dart';

/// Parses a WebVTT storyboard index.
///
/// A storyboard VTT looks like a subtitle file whose payload is an image URL rather than text,
/// optionally carrying a media fragment that crops one thumbnail out of a sprite sheet:
///
/// ```
/// WEBVTT
///
/// 00:00:00.000 --> 00:00:05.000
/// sheet-0.jpg#xywh=0,0,160,90
/// ```
///
/// The parser is deliberately forgiving. These files are generated by a long tail of packaging
/// tools, and one malformed cue in the middle should cost that thumbnail, not the whole preview.
/// Anything it cannot make sense of is skipped and parsing continues.
///
/// [baseUri] is the location the index itself was fetched from; relative payloads resolve
/// against it, which is how nearly every generator writes them.
FStoryboard parseStoryboardVtt(String content, {Uri? baseUri}) {
  final normalized = content
      // A UTF-8 BOM survives decoding as U+FEFF and would otherwise break the header check and,
      // worse, the first cue's timestamps.
      .replaceFirst('﻿', '')
      .replaceAll('\r\n', '\n')
      .replaceAll('\r', '\n');

  final lines = normalized.split('\n');
  final frames = <FStoryboardFrame>[];

  var index = 0;

  // The header is `WEBVTT`, optionally followed by a description, and then an optional metadata
  // block that runs to the first blank line. Files missing the header are still parsed: the cue
  // scan below simply starts at the top.
  if (lines.isNotEmpty && lines.first.trimLeft().startsWith('WEBVTT')) {
    index = 1;
    while (index < lines.length && lines[index].trim().isNotEmpty) {
      index++;
    }
  }

  while (index < lines.length) {
    // Collect one block: consecutive non-blank lines.
    final block = <String>[];
    while (index < lines.length && lines[index].trim().isNotEmpty) {
      block.add(lines[index]);
      index++;
    }
    while (index < lines.length && lines[index].trim().isEmpty) {
      index++;
    }
    if (block.isEmpty) continue;

    final frame = _parseBlock(block, baseUri);
    if (frame != null) frames.add(frame);
  }

  return FStoryboard.of(frames);
}

/// Turns one VTT block into a frame, or null when the block is not a usable cue.
FStoryboardFrame? _parseBlock(List<String> block, Uri? baseUri) {
  final first = block.first.trimLeft();
  // Comment, styling and region blocks carry no cue.
  if (first == 'NOTE' ||
      first.startsWith('NOTE ') ||
      first.startsWith('NOTE\t') ||
      first == 'STYLE' ||
      first == 'REGION') {
    return null;
  }

  final timingIndex = block.indexWhere((line) => line.contains('-->'));
  // No timing line means this is not a cue — or the cue identifier was orphaned by a stray blank
  // line. Either way there is nothing to place on the timeline.
  if (timingIndex < 0) return null;

  final timing = _parseTiming(block[timingIndex]);
  if (timing == null) return null;

  final payload = block
      .skip(timingIndex + 1)
      .map((line) => line.trim())
      .firstWhere((line) => line.isNotEmpty, orElse: () => '');
  if (payload.isEmpty) return null;

  final (url, region) = _splitFragment(payload);
  if (url.isEmpty) return null;

  return FStoryboardFrame(
    start: timing.$1,
    end: timing.$2,
    url: _resolve(url, baseUri),
    region: region,
  );
}

/// Parses a `start --> end` line, ignoring any cue settings trailing the end timestamp.
(Duration, Duration)? _parseTiming(String line) {
  final parts = line.split('-->');
  if (parts.length != 2) return null;

  final start = _parseTimestamp(parts[0]);
  // Cue settings (`align:start`, `line:90%`, …) follow the end timestamp on the same line.
  final endToken = parts[1].trim().split(RegExp(r'\s+')).first;
  final end = _parseTimestamp(endToken);

  if (start == null || end == null || end < start) return null;
  return (start, end);
}

/// Parses `HH:MM:SS.mmm` or `MM:SS.mmm`.
///
/// A comma is accepted in place of the decimal point: SubRip habits leak into generated VTT files
/// often enough that rejecting them would lose real storyboards.
Duration? _parseTimestamp(String raw) {
  final text = raw.trim().replaceAll(',', '.');
  if (text.isEmpty) return null;

  final parts = text.split(':');
  if (parts.length < 2 || parts.length > 3) return null;

  final secondsParts = parts.last.split('.');
  final seconds = int.tryParse(secondsParts.first);
  if (seconds == null) return null;

  var milliseconds = 0;
  if (secondsParts.length > 1) {
    final fraction = secondsParts[1];
    if (fraction.isEmpty || int.tryParse(fraction) == null) return null;
    milliseconds = int.parse(fraction.padRight(3, '0').substring(0, 3));
  }

  final minutes = int.tryParse(parts[parts.length - 2]);
  if (minutes == null) return null;

  var hours = 0;
  if (parts.length == 3) {
    final parsed = int.tryParse(parts.first);
    if (parsed == null) return null;
    hours = parsed;
  }

  return Duration(
    hours: hours,
    minutes: minutes,
    seconds: seconds,
    milliseconds: milliseconds,
  );
}

/// Splits a payload into its image URL and the sprite region it selects.
///
/// Recognises the Media Fragments `xywh` dimension, with or without the `pixel:` prefix. A
/// fragment in any other form is left on the URL rather than discarded — it may be meaningful to
/// whatever serves the image.
/// A fragment that names a region is stripped from the URL whether or not it could be parsed:
/// the URL is what the sprite cache keys on, and a fragment that differs per cue turns every one
/// of a two-hour film's cues into its own cache entry — a fetch and a decode per pointer move,
/// for the same sheet. A fragment that means something else is left alone, as it may matter to
/// whatever serves the image.
(String, Rect?) _splitFragment(String payload) {
  final hash = payload.lastIndexOf('#');
  if (hash < 0) return (payload, null);

  final fragment = payload.substring(hash + 1);
  final withoutFragment = payload.substring(0, hash);

  const key = 'xywh=';
  // Media Fragments joins dimensions with `&`, so the region can arrive next to a `t=` range
  // rather than alone.
  final part = fragment
      .split('&')
      .where((component) => component.startsWith(key))
      .firstOrNull;
  if (part == null) return (payload, null);

  var value = part.substring(key.length);
  if (value.startsWith('pixel:')) {
    value = value.substring('pixel:'.length);
    // Percentage regions cannot be resolved before the sheet is decoded, so they are treated as
    // "no region" and the whole image is shown rather than a wrong crop.
  } else if (value.startsWith('percent:')) {
    return (withoutFragment, null);
  }

  final numbers = value.split(',');
  if (numbers.length != 4) return (withoutFragment, null);

  final parsed = <double>[];
  for (final number in numbers) {
    final component = double.tryParse(number.trim());
    if (component == null) return (withoutFragment, null);
    parsed.add(component);
  }

  if (parsed[2] <= 0 || parsed[3] <= 0) return (withoutFragment, null);

  return (
    withoutFragment,
    Rect.fromLTWH(parsed[0], parsed[1], parsed[2], parsed[3]),
  );
}

/// Resolves a payload URL against the index's own location.
String _resolve(String url, Uri? baseUri) {
  if (baseUri == null) return url;
  try {
    return baseUri.resolve(url).toString();
  } on FormatException {
    // Unparseable payloads are handed through untouched; a caller pointing at a local directory
    // may still be able to open them.
    return url;
  }
}
